# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:

    role_hierarchy:
        ROLE_DELEGUE:     ROLE_ETUDIANT
        ROLE_FORMATEUR :  ROLE ETUDIANT
        ROLE_STAFF :      ROLE ETUDIANT
        ROLE_ADMIN:       ROLE_ETUDIANT, ROLE_FORMATEUR, ROLE_STAFF, ROLE_DELEGUE


    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        in_memory:
            memory: ~
        main:
            id: fos_user.user_provider.username
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern:      ^/
            anonymous:    true
            provider:     main
            form_login:
              login_path: fos_user_security_login
              check_path: fos_user_security_check
            logout:
              path:       fos_user_security_logout
              target:     /ecole
            anonymous:    true
            remember_me:
              secret:     %secret% # %secret% est un paramètre de parameter
            #anonymous: ~
            # activate different ways to authenticate

            # http://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
            #form_login: ~

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }

    encoders:
      Kipskool\Bundle\NewsBundle\Entity\Perso: sha512
      FOS\UserBundle\Model\UserInterface: bcrypt
