# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    #service_name:
    #    class: AppBundle\Directory\ClassName
    #    arguments: ['@another_service_name', 'plain_value', '%parameter_name%']
 # ...
    admin.promo:
        class: Kipskool\Bundle\Admin\PromoAdmin
        arguments: [~, Kipskool\Bundle\NewsBundle\Entity\Promo, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Promo }

    admin.articles_promo:
        class: Kipskool\Bundle\Admin\ArticlesPromoAdmin
        arguments: [~, Kipskool\Bundle\NewsBundle\Entity\Article_promo, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Article_Promo }

    admin.commentaires_articles_promo:
            class: Kipskool\Bundle\Admin\CommentairesArticlesPromoAdmin
            arguments: [~, Kipskool\Bundle\NewsBundle\Entity\Commentaire_article_promo, ~]
            tags:
                - { name: sonata.admin, manager_type: orm, label: Commentaire_Article_Promo }