# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    #service_name:
    #    class: AppBundle\Directory\ClassName
    #    arguments: ['@another_service_name', 'plain_value', '%parameter_name%']
 admin.perso:
        class: Kipskool\Bundle\Admin\PersoAdmin
        arguments: [~, Kipskool\Bundle\NewsBundle\Entity\Perso, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Perso }