# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    #service_name:
    #    class: AppBundle\Directory\ClassName
    #    arguments: ['@another_service_name', 'plain_value', '%parameter_name%']
 # ...
    admin.promo:
        class: Kipskool\Bundle\Admin\PromoAdmin
        arguments: [~, Kipskool\Bundle\NewsBundle\Entity\Promo, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Promo }
    admin.perso:
        class: Kipskool\Bundle\Admin\PersoAdmin
        arguments: [~, Kipskool\Bundle\NewsBundle\Entity\Perso, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Perso }

    admin.articles_promo:
        class: Kipskool\Bundle\Admin\ArticlesPromoAdmin
        arguments: [~, Kipskool\Bundle\NewsBundle\Entity\Article_promo, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Article_Promo }

    admin.commentaires_articles_promo:
            class: Kipskool\Bundle\Admin\CommentairesArticlesPromoAdmin
            arguments: [~, Kipskool\Bundle\NewsBundle\Entity\Commentaire_article_promo, ~]
            tags:
                - { name: sonata.admin, manager_type: orm, label: Commentaire_Article_Promo }
    admin.articles_perso:
        class: Kipskool\Bundle\Admin\ArticlePersoAdmin
        arguments: [~, Kipskool\Bundle\NewsBundle\Entity\ArticlePerso, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Article_Perso }

    admin.commentaire_perso:
        class: Kipskool\Bundle\Admin\CommentaireArticlePersoAdmin
        arguments: [~, Kipskool\Bundle\NewsBundle\Entity\CommentaireArticlePerso, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Commentaire_Perso}

    admin.ecole:
        class: Kipskool\Bundle\Admin\EcoleAdmin
        arguments: [~, Kipskool\Bundle\NewsBundle\Entity\Ecole, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Ecole}

    admin.article_ecole:
        class: Kipskool\Bundle\Admin\ArticleEcoleAdmin
        arguments: [~, Kipskool\Bundle\NewsBundle\Entity\articleEcole, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Article_Ecole}

    admin.commentaire_ecole:
        class: Kipskool\Bundle\Admin\CommentaireArticleEcoleAdmin
        arguments: [~, Kipskool\Bundle\NewsBundle\Entity\commentaireArticleEcole, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Commentaire_Ecole}

    kipskool_news.raccourci_texte:
        class: Kipskool\Bundle\Extrait\Extrait

    kipskool_news.twig_extension:
        class: Kipskool\Bundle\Extrait\TwigExtension
        public: false
        tag:
            - { name: twig.extension }

