# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value
    image_directory: NewsBundle\img

services:
    #service_name:
    #    class: AppBundle\Directory\ClassName
    #    arguments: ['@another_service_name', 'plain_value', '%parameter_name%']
 # ...
    admin.promo:
        class: Admin\PromoAdmin
        arguments: [~, NewsBundle\Entity\Promo, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Promo }
    admin.perso:
        class: Admin\PersoAdmin
        arguments: [~, NewsBundle\Entity\Perso, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Perso }

    admin.articles_promo:
        class: Admin\ArticlesPromoAdmin
        arguments: [~, NewsBundle\Entity\Article_promo, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Article_Promo }

    admin.commentaires_articles_promo:
            class: Admin\CommentairesArticlesPromoAdmin
            arguments: [~, NewsBundle\Entity\Commentaire_article_promo, ~]
            tags:
                - { name: sonata.admin, manager_type: orm, label: Commentaire_Article_Promo }
    admin.articles_perso:
        class: Admin\ArticlePersoAdmin
        arguments: [~, NewsBundle\Entity\ArticlePerso, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Article_Perso }

    admin.commentaire_perso:
        class: Admin\CommentaireArticlePersoAdmin
        arguments: [~, NewsBundle\Entity\CommentaireArticlePerso, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Commentaire_Perso}

    admin.ecole:
        class: Admin\EcoleAdmin
        arguments: [~, NewsBundle\Entity\Ecole, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Ecole}

    admin.article_ecole:
        class: Admin\ArticleEcoleAdmin
        arguments: [~, NewsBundle\Entity\articleEcole, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Article_Ecole}

    admin.commentaire_ecole:
        class: Admin\CommentaireArticleEcoleAdmin
        arguments: [~, NewsBundle\Entity\commentaireArticleEcole, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Commentaire_Ecole}

    kipskool_news.raccourci_texte:
        class: NewsBundle\Twig\AppExtension
        public: false
        tags:
            - { name: twig.extension}

    app.twig_extension:
        class: NewsBundle\Twig\AppExtension
        public: false
        tag:
            - { name: twig.extension }

    app.form.registration:
      class: NewsBundle\Form\RegistrationType
      tags:
          - { name: form.type, alias: app_user_registration }

    app.srcFeatur_uploader:
        class: NewsBundle\FileUpLoader
        arguments: ['%srcfeatures_directory%']
