# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    #service_name:
    #    class: AppBundle\Directory\ClassName
    #    arguments: ['@another_service_name', 'plain_value', '%parameter_name%']
    admin.perso:
        class: Kipskool\Bundle\Admin\PersoAdmin
        arguments: [~, Kipskool\Bundle\NewsBundle\Entity\Perso, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Perso }

    admin.articles_perso:
        class: Kipskool\Bundle\Admin\ArticlePersoAdmin
        arguments: [~, Kipskool\Bundle\NewsBundle\Entity\ArticlePerso, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Article_Perso }

    admin.commentaire_perso:
        class: Kipskool\Bundle\Admin\CommentaireArticlePersoAdmin
        arguments: [~, Kipskool\Bundle\NewsBundle\Entity\CommentaireArticlePerso, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Commentaire_Perso}