<?php

namespace NewsBundle\Repository;

/**
 * ArticlePersoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticlePersoRepository extends \Doctrine\ORM\EntityRepository
{

    public function findPersoPostedArticle($perso){
        return $this->createQueryBuilder('article')


            ->where('article.auteur = :perso')
            ->setParameter('perso', $perso)
            ->getQuery()
            ->getResult()

            ;
    }

}
