<?php

namespace NewsBundle\Repository;

/**
 * articleEcoleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class articleEcoleRepository extends \Doctrine\ORM\EntityRepository
{
}
