<?php

namespace NewsBundle\Repository;

/**
 * CommentaireArticlePersoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentaireArticlePersoRepository extends \Doctrine\ORM\EntityRepository
{
}
