<?php

namespace NewsBundle\Repository;

/**
 * commentaireArticleEcoleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class commentaireArticleEcoleRepository extends \Doctrine\ORM\EntityRepository
{
}
