<?php

namespace NewsBundle\Repository;

/**
 * Commentaire_article_promoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Commentaire_article_promoRepository extends \Doctrine\ORM\EntityRepository
{
}
