<?php

namespace Kipskool\Bundle\NewsBundle\Repository;

/**
 * Article_promoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Article_promoRepository extends \Doctrine\ORM\EntityRepository
{
}
